import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:diabetes/models/food_model.dart';
import 'package:diabetes/models/meal_model.dart';
import 'package:diabetes/providers/auth_provider.dart';
import 'package:diabetes/providers/patient_provider.dart';
import 'package:diabetes/services/database_service.dart';
import 'package:diabetes/services/food_service.dart';

class AddFoodScreen extends StatefulWidget {
  final String? mealTimeId;

  const AddFoodScreen({super.key, this.mealTimeId});

  @override
  State<AddFoodScreen> createState() => _AddFoodScreenState();
}

class _AddFoodScreenState extends State<AddFoodScreen> {
  // Services
  final FoodService _foodService = FoodService();
  final DatabaseService _databaseService = DatabaseService();

  // State variables
  List<FoodModel> _allFoods = [];
  List<FoodModel> _filteredFoods = [];
  bool _isLoading = true;
  bool _isSaving = false;

  // Selection state
  String? _selectedMealTime;
  FoodModel? _selectedFood;
  final TextEditingController _weightController = TextEditingController();
  final TextEditingController _searchController = TextEditingController();
  final FocusNode _weightFocusNode = FocusNode();

  // TEMA WARNA (Hijau Fresh Nature - Sesuai Dashboard)
  final Color _primaryGreen = const Color(0xFF66BB6A);
  final Color _darkGreen = const Color(0xFF2E7D32);

  // Warna Nutrisi
  final Color colCarbs = const Color(0xFF2196F3);
  final Color colCals = const Color(0xFFFF9800);
  final Color colProt = const Color(0xFF4CAF50);
  final Color colFat = const Color(0xFFF44336);

  final List<Map<String, dynamic>> mealTimes = [
    {'id': 'morning', 'name': 'Pagi', 'icon': Icons.wb_sunny_rounded},
    {'id': 'lunch', 'name': 'Siang', 'icon': Icons.wb_sunny_outlined},
    {'id': 'dinner', 'name': 'Malam', 'icon': Icons.nightlight_round},
    {'id': 'snack', 'name': 'Camilan', 'icon': Icons.cookie_outlined},
  ];

  @override
  void initState() {
    super.initState();
    _selectedMealTime = widget.mealTimeId;
    _fetchFoods();
  }

  @override
  void dispose() {
    _weightController.dispose();
    _searchController.dispose();
    _weightFocusNode.dispose();
    super.dispose();
  }

  Future<void> _fetchFoods() async {
    try {
      final foods = await _foodService.getAllFoods();
      if (mounted) {
        setState(() {
          _allFoods = foods;
          _filteredFoods = foods;
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoading = false);
        _showSnackBar('Gagal memuat data makanan: $e', isError: true);
      }
    }
  }

  void _filterFoods(String query) {
    setState(() {
      if (query.isEmpty) {
        _filteredFoods = _allFoods;
      } else {
        _filteredFoods = _allFoods
            .where(
              (food) => food.name.toLowerCase().contains(query.toLowerCase()),
            )
            .toList();
      }
    });
  }

  double _calculateValue(double valuePer100g) {
    double weight = double.tryParse(_weightController.text) ?? 0;
    if (weight < 0) weight = 0;
    return (valuePer100g * weight) / 100;
  }

  Future<void> _saveFood() async {
    // Validate Inputs
    if (_selectedFood == null) {
      _showSnackBar('Silakan pilih makanan terlebih dahulu', isError: true);
      return;
    }
    if (_selectedMealTime == null) {
      _showSnackBar('Silakan pilih waktu makan', isError: true);
      return;
    }
    double weight = double.tryParse(_weightController.text) ?? 0;
    if (weight <= 0) {
      _showSnackBar(
        'Masukkan berat makanan yang valid (minimal 1g)',
        isError: true,
      );
      _weightFocusNode.requestFocus();
      return;
    }

    final authProvider = context.read<AuthProvider>();
    final user = authProvider.currentUser;

    if (user == null) {
      _showSnackBar('Sesi habis, silakan login ulang', isError: true);
      return;
    }

    setState(() => _isSaving = true);
    FocusScope.of(context).unfocus();

    try {
      // Calculate totals
      final double totalCarbs = _calculateValue(_selectedFood!.carbs);
      final double totalCalories = _calculateValue(_selectedFood!.calories);
      final double totalProtein = _calculateValue(_selectedFood!.protein);
      final double totalFat = _calculateValue(_selectedFood!.fat);

      // Create FoodItemModel
      final foodItem = FoodItemModel(
        foodId: _selectedFood!.id,
        foodName: _selectedFood!.name,
        weight: weight,
        carbs: totalCarbs,
        calories: totalCalories,
        protein: totalProtein,
        fat: totalFat,
      );

      // Create MealModel
      final newMeal = MealModel(
        id: '', // Generated by Firestore
        userId: user.id,
        date: DateTime.now(),
        mealTime: _selectedMealTime!,
        foods: [foodItem],
        totalCarbs: totalCarbs,
        totalCalories: totalCalories,
        totalProtein: totalProtein,
        totalFat: totalFat,
      );

      // Save to Database
      await _databaseService.addMeal(newMeal);

      if (mounted) {
        await context.read<PatientProvider>().refreshData(user.id);

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const Icon(Icons.check_circle, color: Colors.white),
                const SizedBox(width: 8),
                Expanded(
                  child: Text('${_selectedFood!.name} berhasil ditambahkan!'),
                ),
              ],
            ),
            backgroundColor: _darkGreen,
            behavior: SnackBarBehavior.floating,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        );
        Navigator.pop(context);
      }
    } catch (e) {
      _showSnackBar(
        'Gagal menyimpan: ${e.toString().replaceAll('Exception: ', '')}',
        isError: true,
      );
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  void _showSnackBar(String message, {bool isError = false}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            Icon(
              isError ? Icons.error_outline : Icons.check_circle,
              color: Colors.white,
            ),
            const SizedBox(width: 8),
            Expanded(child: Text(message)),
          ],
        ),
        backgroundColor: isError ? Colors.red.shade600 : _darkGreen,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF5F7FA),
      appBar: AppBar(
        title: const Text(
          'Catat Makanan',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        backgroundColor: Colors.white,
        foregroundColor: const Color(0xFF212121),
        elevation: 0.5,
        centerTitle: true,
      ),
      body: Column(
        children: [
          // --- SEARCH BAR ---
          Container(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
            decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.vertical(bottom: Radius.circular(20)),
            ),
            child: TextField(
              controller: _searchController,
              onChanged: _filterFoods,
              decoration: InputDecoration(
                hintText: 'Cari nama makanan...',
                hintStyle: TextStyle(color: Colors.grey.shade400),
                prefixIcon: Icon(Icons.search, color: _primaryGreen),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: BorderSide.none,
                ),
                filled: true,
                fillColor: Colors.grey.shade100,
                contentPadding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 14,
                ),
                suffixIcon: _searchController.text.isNotEmpty
                    ? IconButton(
                        icon: const Icon(Icons.clear, color: Colors.grey),
                        onPressed: () {
                          _searchController.clear();
                          _filterFoods('');
                          FocusScope.of(context).unfocus();
                        },
                      )
                    : null,
              ),
            ),
          ),

          Expanded(
            child: _isLoading
                ? Center(child: CircularProgressIndicator(color: _primaryGreen))
                : SingleChildScrollView(
                    physics: const BouncingScrollPhysics(),
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // --- WAKTU MAKAN ---
                        _buildSectionTitle('Waktu Makan'),
                        const SizedBox(height: 12),
                        _buildMealTimeGrid(),
                        const SizedBox(height: 24),

                        // --- INPUT FORM (HERO SECTION) ---
                        if (_selectedFood != null) ...[
                          _buildSelectedFoodForm(),
                          const SizedBox(height: 24),
                        ],

                        // --- DAFTAR MAKANAN ---
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            _buildSectionTitle('Daftar Makanan'),
                            Text(
                              '${_filteredFoods.length} item',
                              style: TextStyle(
                                color: Colors.grey.shade600,
                                fontSize: 12,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),

                        _filteredFoods.isEmpty
                            ? _buildEmptyState()
                            : ListView.builder(
                                shrinkWrap: true,
                                physics: const NeverScrollableScrollPhysics(),
                                itemCount: _filteredFoods.length,
                                itemBuilder: (context, index) {
                                  return _buildFoodCard(_filteredFoods[index]);
                                },
                              ),
                        const SizedBox(height: 30),
                      ],
                    ),
                  ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(
        fontSize: 16,
        fontWeight: FontWeight.bold,
        color: Color(0xFF212121),
      ),
    );
  }

  Widget _buildEmptyState() {
    return Container(
      padding: const EdgeInsets.all(32.0),
      alignment: Alignment.center,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.fastfood_outlined, size: 64, color: Colors.grey.shade300),
          const SizedBox(height: 16),
          Text(
            "Tidak ditemukan makanan.",
            style: TextStyle(color: Colors.grey.shade600),
          ),
        ],
      ),
    );
  }

  Widget _buildMealTimeGrid() {
    return GridView.builder(
      shrinkWrap: true,
      physics: const NeverScrollableScrollPhysics(),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 4,
        crossAxisSpacing: 8,
        mainAxisSpacing: 8,
        childAspectRatio: 0.85,
      ),
      itemCount: mealTimes.length,
      itemBuilder: (context, index) {
        final meal = mealTimes[index];
        bool isSelected = _selectedMealTime == meal['id'];

        return AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          curve: Curves.easeInOut,
          child: Material(
            color: Colors.transparent,
            child: InkWell(
              onTap: () => setState(() => _selectedMealTime = meal['id']),
              borderRadius: BorderRadius.circular(16),
              child: Container(
                decoration: BoxDecoration(
                  color: isSelected ? _primaryGreen : Colors.white,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(
                    color: isSelected ? _primaryGreen : Colors.grey.shade200,
                    width: 1.5,
                  ),
                  boxShadow: isSelected
                      ? [
                          BoxShadow(
                            color: _primaryGreen.withOpacity(0.3),
                            blurRadius: 8,
                            offset: const Offset(0, 4),
                          ),
                        ]
                      : [],
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(
                      meal['icon'] as IconData,
                      size: 28,
                      color: isSelected ? Colors.white : _primaryGreen,
                    ),
                    const SizedBox(height: 8),
                    Text(
                      meal['name'],
                      style: TextStyle(
                        fontSize: 12,
                        color: isSelected ? Colors.white : Colors.grey.shade700,
                        fontWeight: isSelected
                            ? FontWeight.w600
                            : FontWeight.normal,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildSelectedFoodForm() {
    if (_weightController.text.isEmpty) {
      _weightController.text = '';
    }

    return Card(
      elevation: 4,
      shadowColor: Colors.black.withOpacity(0.1),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      child: Column(
        children: [
          // Header Card
          Container(
            padding: const EdgeInsets.fromLTRB(20, 16, 16, 16),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [
                  _primaryGreen,
                  const Color(0xFF81C784),
                ], // Green Gradient
              ),
              borderRadius: const BorderRadius.vertical(
                top: Radius.circular(20),
              ),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Expanded(
                  child: Row(
                    children: [
                      const SizedBox(width: 12),
                      Expanded(
                        child: Text(
                          _selectedFood!.name,
                          style: const TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ],
                  ),
                ),
                IconButton(
                  onPressed: () {
                    setState(() {
                      _selectedFood = null;
                      _weightController.clear();
                    });
                    FocusScope.of(context).unfocus();
                  },
                  icon: const Icon(Icons.close, color: Colors.white),
                ),
              ],
            ),
          ),

          Container(
            padding: const EdgeInsets.all(20),
            color: Colors.white,
            child: Column(
              children: [
                // Input Berat
                Row(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Expanded(
                      child: TextField(
                        controller: _weightController,
                        focusNode: _weightFocusNode,
                        keyboardType: const TextInputType.numberWithOptions(
                          decimal: true,
                        ),
                        textAlign: TextAlign.center,
                        style: const TextStyle(
                          fontSize: 40,
                          fontWeight: FontWeight.w800,
                          color: Color(0xFF212121),
                        ),
                        decoration: InputDecoration(
                          hintText: '0',
                          hintStyle: TextStyle(color: Colors.grey.shade300),
                          border: InputBorder.none,
                          contentPadding: EdgeInsets.zero,
                        ),
                        onChanged: (_) => setState(() {}),
                      ),
                    ),
                    const Text(
                      'gram',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w500,
                        color: Colors.grey,
                      ),
                    ),
                  ],
                ),
                const Divider(height: 24, thickness: 1),

                // Real-time Nutrition Preview
                const Padding(
                  padding: EdgeInsets.only(bottom: 12.0),
                  child: Text(
                    "Total Nutrisi:",
                    style: TextStyle(
                      fontWeight: FontWeight.w500,
                      color: Colors.grey,
                    ),
                  ),
                ),
                Row(
                  children: [
                    _buildLiveNutrientCard(
                      'Karbo',
                      _calculateValue(_selectedFood!.carbs),
                      'g',
                      colCarbs,
                      Icons.grain,
                    ),
                    const SizedBox(width: 12),
                    _buildLiveNutrientCard(
                      'Kalori',
                      _calculateValue(_selectedFood!.calories),
                      'kcal',
                      colCals,
                      Icons.local_fire_department,
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                Row(
                  children: [
                    _buildLiveNutrientCard(
                      'Protein',
                      _calculateValue(_selectedFood!.protein),
                      'g',
                      colProt,
                      Icons.fitness_center,
                    ),
                    const SizedBox(width: 12),
                    _buildLiveNutrientCard(
                      'Lemak',
                      _calculateValue(_selectedFood!.fat),
                      'g',
                      colFat,
                      Icons.water_drop,
                    ),
                  ],
                ),

                const SizedBox(height: 24),

                // Save Button
                SizedBox(
                  width: double.infinity,
                  height: 54,
                  child: ElevatedButton(
                    onPressed: _isSaving ? null : _saveFood,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: _primaryGreen,
                      elevation: _isSaving ? 0 : 4,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(16),
                      ),
                    ),
                    child: _isSaving
                        ? const SizedBox(
                            height: 24,
                            width: 24,
                            child: CircularProgressIndicator(
                              color: Colors.white,
                              strokeWidth: 2.5,
                            ),
                          )
                        : Text(
                            _selectedMealTime == null
                                ? 'Pilih Waktu Makan Dahulu'
                                : 'Tambahkan ke ${mealTimes.firstWhere((m) => m['id'] == _selectedMealTime)['name']}',
                            style: const TextStyle(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildLiveNutrientCard(
    String label,
    double value,
    String unit,
    Color color,
    IconData icon,
  ) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 8),
        decoration: BoxDecoration(
          color: color.withOpacity(0.08),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: color.withOpacity(0.2)),
        ),
        child: Column(
          children: [
            Icon(icon, size: 20, color: color),
            const SizedBox(height: 6),
            Text(
              label,
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey.shade700,
                fontWeight: FontWeight.w500,
              ),
            ),
            const SizedBox(height: 4),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                Text(
                  value.toStringAsFixed(value == 0 ? 0 : 1),
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.w800,
                    color: color,
                  ),
                ),
                const SizedBox(width: 2),
                Padding(
                  padding: const EdgeInsets.only(bottom: 2.0),
                  child: Text(
                    unit,
                    style: TextStyle(
                      fontSize: 12,
                      color: color.withOpacity(0.8),
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFoodCard(FoodModel food) {
    bool isSelected = _selectedFood?.id == food.id;

    return InkWell(
      onTap: () {
        setState(() => _selectedFood = food);
        Future.delayed(const Duration(milliseconds: 100), () {
          if (_weightController.text.isEmpty) {
            _weightFocusNode.requestFocus();
          }
        });
      },
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(
            color: isSelected ? _primaryGreen : Colors.transparent,
            width: 2,
          ),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.05),
              blurRadius: 8,
              offset: const Offset(0, 2),
            ),
          ],
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        food.name,
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                          color: Color(0xFF212121),
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        'Per 100 gram',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.grey.shade500,
                          fontStyle: FontStyle.italic,
                        ),
                      ),
                    ],
                  ),
                ),
                // Text menggantikan icon check
                if (isSelected)
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 6,
                    ),
                    decoration: BoxDecoration(
                      color: _primaryGreen,
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: const Text(
                      'Dipilih',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                      ),
                    ),
                  ),
              ],
            ),
            const SizedBox(height: 12),
            // Nutrient Row without Icons
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                _buildSimpleNutrientInfo('Karbo', '${food.carbs}g'),
                _buildSimpleNutrientInfo('Kalori', '${food.calories.toInt()}'),
                _buildSimpleNutrientInfo('Protein', '${food.protein}g'),
                _buildSimpleNutrientInfo('Lemak', '${food.fat}g'),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSimpleNutrientInfo(String label, String value) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(fontSize: 10, color: Color(0xFF757575)),
        ),
        const SizedBox(height: 2),
        Text(
          value,
          style: const TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.bold,
            color: Color(0xFF212121),
          ),
        ),
      ],
    );
  }
}
